# Generated by Django 4.1.3 on 2023-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physical_AT_Table',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CIRCLE', models.CharField(max_length=100)),
                ('SITE_ID', models.CharField(max_length=100)),
                ('UNIQUE_ID', models.CharField(max_length=100)),
                ('ENODEB_ID', models.CharField(max_length=100)),
                ('BAND', models.CharField(max_length=100)),
                ('Circle_Project', models.CharField(max_length=100)),
                ('OEM_NAME_Nokia_ZTE_Ericsson_Huawei', models.CharField(max_length=100)),
                ('MS1', models.DateField(null=True)),
                ('PHYSICAL_AT_Offered_DATE', models.DateField(null=True)),
                ('PHYSICAL_AT_Status_Accepted_Rejected_Offered_Pending_Dismantle', models.CharField(max_length=100)),
                ('CURRENT_STATUS_OF_SITE', models.CharField(max_length=100)),
                ('Total_Allocation', models.CharField(max_length=100)),
                ('Project', models.CharField(max_length=100)),
                ('Current_PHY_AT_Status', models.CharField(max_length=100)),
                ('Expected_Closer_Date', models.DateField(null=True)),
                ('Additional_PHY_AT_Remarks', models.CharField(max_length=100)),
                ('Ericsson_AT_Status', models.CharField(max_length=100)),
                ('Ericsson_PHY_AT_Date', models.DateField(null=True)),
                ('Huawei_PHY_AT_Status', models.CharField(max_length=100)),
                ('Huawei_PHY_AT_Date', models.DateField(null=True)),
                ('Nokia_PHY_AT_Status', models.CharField(max_length=100)),
                ('Nokia_PHY_AT_Date', models.DateField(null=True)),
                ('Samsung_PHY_AT_Status', models.CharField(max_length=100)),
                ('Samsung_PHY_AT_Date', models.DateField(null=True)),
                ('ZTE_PHY_AT_Status', models.CharField(max_length=100)),
                ('ZTE_PHY_AT_Date', models.DateField(null=True)),
                ('MS1_to_PHY_AT_Ageing', models.CharField(max_length=100)),
                ('Ageing', models.CharField(max_length=100)),
                ('Plan_Date', models.DateField(null=True)),
                ('Plan_Status', models.CharField(max_length=100)),
            ],
        ),
    ]
