# Generated by Django 4.1.3 on 2023-05-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Physical_AT_APP', '0004_physical_at_table_physical_at_acceptance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physical_at_table',
            old_name='Ericsson_AT_Status',
            new_name='Ericsson_PHY_AT_Status',
        ),
    ]
