# Generated by Django 4.1.3 on 2023-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physical_AT_APP', '0005_rename_ericsson_at_status_physical_at_table_ericsson_phy_at_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_at_table',
            name='Ericsson_PHY_AT_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Expected_Closer_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Huawei_PHY_AT_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Nokia_PHY_AT_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='PHYSICAL_AT_ACCEPTANCE_DATE',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='PHYSICAL_AT_Offered_DATE',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Plan_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Samsung_PHY_AT_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='ZTE_PHY_AT_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
