# Generated by Django 4.1.3 on 2023-05-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physical_AT_APP', '0008_physical_at_table_current_phy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physical_at_table',
            name='Current_PHY_Status',
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='SITE_ID',
            field=models.CharField(max_length=500),
        ),
    ]
