# Generated by Django 4.1.3 on 2023-05-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physical_AT_APP', '0009_remove_physical_at_table_current_phy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_at_table',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
