# Generated by Django 4.1.3 on 2023-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physical_AT_APP', '0010_alter_physical_at_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_at_table',
            name='Additional_PHY_AT_Remarks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Ageing',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='BAND',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='BTS_TYPE',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='CIRCLE',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='CURRENT_STATUS_OF_SITE',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Circle_Project',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Current_PHY_AT_Status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='ENODEB_ID',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Ericsson_PHY_AT_Status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Huawei_PHY_AT_Status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='MS1_to_PHY_AT_Ageing',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Nokia_PHY_AT_Status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='OEM_NAME_Nokia_ZTE_Ericsson_Huawei',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='PHYSICAL_AT_Status_Accepted_Rejected_Offered_Pending_Dismantle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Plan_Status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Project',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Samsung_PHY_AT_Status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='Total_Allocation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='UNIQUE_ID',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='physical_at_table',
            name='ZTE_PHY_AT_Status',
            field=models.CharField(max_length=500),
        ),
    ]
