# Generated by Django 4.1.3 on 2023-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physical_AT_APP', '0011_alter_physical_at_table_additional_phy_at_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_at_upload_status',
            name='Remark',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_upload_status',
            name='Site_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='physical_at_upload_status',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='physical_at_upload_status',
            name='update_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
