# Generated by Django 4.1.3 on 2023-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Physical_AT_APP', '0012_alter_physical_at_upload_status_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_at_table',
            name='Expected_Closer_Status',
            field=models.CharField(default='2', max_length=500),
            preserve_default=False,
        ),
    ]
